# Builder image
FROM napnap75/rpi-alpine-base:latest as builder

# Download the required software
RUN apk add --no-cache git musl-dev go \
  && git clone https://github.com/restic/restic \
  && cd restic \
  && go run build.go

# Final image
FROM napnap75/rpi-alpine-base:latest

# Download the required software
RUN apk add --no-cache curl openssh-client

# Define default command
COPY --from=builder restic/restic /usr/bin
COPY docker-backup.sh /usr/bin
CMD ["/usr/bin/docker-backup.sh"]
